name: sketch_pad
description: An experimental redux of the DartPad UI.
publish_to: 'none'

environment:
  sdk: ^3.2.0

dependencies:
  codemirror: any
  collection: any
  dartpad_shared: any
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  fluttering_phrases: ^1.0.0
  go_router: ^12.1.0
  http: any
  json_annotation: ^4.8.1
  localstorage: ^4.0.1+4
  lottie: ^3.0.0
  pointer_interceptor: ^0.9.0
  provider: ^6.0.0
  split_view: ^3.2.0
  url_launcher: any
  url_strategy: any
  vtable: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/dart_logo_128.png
    - assets/flutter_logo_192.png
    - assets/animations/load_animation.json
    - assets/animations/success_animation.json
    - assets/animations/warning_animation.json
    - assets/

dependency_overrides:
  dartpad_shared:
    path: ../dartpad_shared
